Repository AndrewEllen/instagram-clone, pull requests merged in 2023-07, with the labels that each got.

#17 Merging f/minor UI adjustments to Dev Task ID: CU-863h4pztu
  lib/pages/Login/user_login_page.dart
  lib/pages/UserRegistration/user_registration_email_signup.dart
  lib/pages/UserRegistration/user_registration_page.dart
Labels: enhancement

#19 f/Fix-linting-errors-CU-862k2rf6j
  lib/extensions/email_validator.dart
  lib/main.dart
  lib/pages/Home/home_page.dart
  lib/pages/Profile/profile_page.dart
  lib/pages/UserRegistration/user_registration_email_signup.dart
  lib/pages/main_page.dart
  lib/providers/Profile/user_data.dart
  lib/widgets/HomeWidgets/comment_modal_screen.dart
  lib/widgets/HomeWidgets/home_feed_post_card.dart
  lib/widgets/HomeWidgets/share_modal_screen.dart
  lib/widgets/MainAppWidgets/bottom_modal_share_tile.dart
  lib/widgets/MainAppWidgets/comment_button.dart
  lib/widgets/MainAppWidgets/favourite_button.dart
  lib/widgets/MainAppWidgets/like_button.dart
  lib/widgets/MainAppWidgets/nav_bar.dart
  lib/widgets/MainAppWidgets/share_button.dart
  lib/widgets/ProfileWidgets/PostsGridView.dart
  lib/widgets/ProfileWidgets/bottom_modal_edit_bar.dart
  lib/widgets/ProfileWidgets/bottom_modal_share_bar.dart
  lib/widgets/ProfileWidgets/edit_profile_text_form.dart
  lib/widgets/ProfileWidgets/post_tile.dart
  lib/widgets/ProfileWidgets/posts_grid_view.dart
  lib/widgets/ProfileWidgets/profile_buttons.dart
  lib/widgets/ProfileWidgets/profile_counters.dart
Labels: bugfix

#20 Merge f/pipeline implementation to dev
  .github/workflows/flutter-ci-cd.yml
Labels: enhancement

#21 Daily log 03/07/2023 - Lewis
  Team/DailyLogs/Lewis/2023-07-03.md
  Team/DailyLogs/Lewis/assets/2023-07-03-PR.png
  Team/DailyLogs/Lewis/assets/2023-07-03-task.png
  Team/DailyLogs/Lewis/assets/2023-07-03-ui-update.gif
Labels: Daily Log

#34 Merge f/new-landing-page-design to dev
  Team/Screenshots/ClickUp/teamtaskmanagement2.png
  lib/pages/LandingPage/landing_page.dart
  lib/pages/Login/user_login_page.dart
  lib/pages/UserRegistration/user_registration_confirmation_email.dart
  lib/pages/UserRegistration/user_registration_confirmation_page.dart
  lib/pages/UserRegistration/user_registration_page.dart
  lib/pages/UserRegistration/user_signup.dart
Labels: enhancement
